spring:
  application:
    name: match-carreira-api

  # --- CONFIGURACAO DE E-MAIL (MAILTRAP) ---
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:seu_user_fake}
    password: ${MAIL_PASSWORD:sua_senha_fake}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # --- CONFIGURACAO DO BANCO DE DADOS ---
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/match_carreira_db
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password123}
    driver-class-name: org.postgresql.Driver

  # --- CONFIGURACAO DO JPA / HIBERNATE ---
  jpa:
    hibernate:

      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  # --- CACHE (REDIS) ---
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# --- CONFIGURACAO DO SWAGGER (SPRINGDOC) ---
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs

# --- SEGURANCA CUSTOMIZADA ---
api:
  security:
    token:
      secret: ${JWT_SECRET:match-carreira-secret-key-32-chars-minimum}

# --- LOGGING ---
logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO